### ISSUE TITLE
[Bug] Crash when opening any chapter

### ISSUE THREAD

**Issue by joseph619** [rajarsheechatterjee/lnreader#10]
App version: 1.0.15
Device - Galaxy Tab S7
Android version - 11

##Steps to reproduce 
1. Open any manga 
2. Open any chapter

##Issue
App crashes

##Other
Could maybe add dump crashlog feature from Tachiyomi for easier troubleshooting in future, perhaps?

**Comment by rajarsheechatterjee** [comment]
I can't reproduce the issue as the app is working fine on my device.  I have never tested the app on a tablet so it could be a tablet specific issue. 

Yes, I should add dump crashlog feature as right now I cannot identify the problem.

**Comment by joseph619** [comment]
The issue is the same on my Galaxy S10+ phone (Android 11), so it's not just the tablet.

**Comment by rajarsheechatterjee** [comment]
Can you download the latest release [v1.0.16](https://github.com/rajarsheechatterjee/lnreader/releases/tag/v1.0.16) and check if it still happens?

If you had downloaded v1.0.11 previously, in that version OTA updates were not disabled so your app will get updated to the latest but not work. I disabled automatic updated in  v1.0.13.

If the latest still does not work can you can access the [API](https://lnreader-extensions.vercel.app/)?

**Comment by joseph619** [comment]
I uninstalled and reinstalled the app (v1.0.16) the reader seems to be working now!

I will open a new ticket for the dump crashlog then
