### ISSUE TITLE
[Feature Request] Add a scrollbar on the side

### ISSUE THREAD

**Issue by BreadGenie** [rajarsheechatterjee/lnreader#17]
It doesn't have to be scrollable. Just as an indicator to know how much of the chapter I've read. Also it'd be nice if it pops up only while scrolling on the page and fades away when the page is still.

**Comment by rajarsheechatterjee** [comment]
The scroll indicator is present but not visible in the dark background so I have added percentage at the bottom to show the progress.

![Screenshot_20210510-181248__01](https://user-images.githubusercontent.com/57822170/117662158-e3dfe000-b1bc-11eb-8a5f-894b4081b9d7.jpg)

![Screenshot_20210510-181316](https://user-images.githubusercontent.com/57822170/117661687-4edce700-b1bc-11eb-8787-3aae677c1247.jpg)
