### ISSUE TITLE
[Feature Request] Mark Chapters as read

### ISSUE THREAD

**Issue by TronTheGamer** [rajarsheechatterjee/lnreader#18]
It would be great if we could mark chapters as read by long pressing the chapter in the novel screen or by swiping the chapter no. (Like in tachiyomi j2k). 

Thanks in advanced.

**Comment by joseph619** [comment]
I would prefer swiping to mark read/unread and bookmark also (like on J2K)

**Comment by rajarsheechatterjee** [comment]
I tested swiping to mark read/unread and bookmark. It was working smoothly if the novel had less than 100 chapters but begins to lag if the chapter list is long. So I decided to add a bottom sheet(like J2K) for those actions.

<img src="https://user-images.githubusercontent.com/57822170/118344092-323d0800-b54a-11eb-9154-e45eefb52152.jpg" width="400" >

I will add swiping in future if it works smoothly for a long chapter list.
