### ISSUE TITLE
Continue reading resets to a different chapter then last read

### ISSUE THREAD

**Issue by BreadGenie** [rajarsheechatterjee/lnreader#19]
This is how it is initially

![Screenshot_20210512-113549.png](https://user-images.githubusercontent.com/63963181/117926440-64feba80-b316-11eb-8d2e-8a795fd55dd4.png)

After opening a different novel

![Screenshot_20210512-113604.png](https://user-images.githubusercontent.com/63963181/117926527-88c20080-b316-11eb-9773-b598eccf8c8f.png)

The values at the history sections are right though.

![Screenshot_20210512-113609.png](https://user-images.githubusercontent.com/63963181/117926573-99727680-b316-11eb-8417-0daa79afabc9.png)

**Comment by rajarsheechatterjee** [comment]
Found the problem and fixed it. It should also fix sort/filters getting reset.
