### ISSUE TITLE
[Bug]Stuck on Opening Logo Screen

### ISSUE THREAD

**Issue by RoyalPK04** [rajarsheechatterjee/lnreader#20]
![Screenshot_2021-05-12-18-58-08-23_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/75008274/117983169-52a37180-b354-11eb-9611-3189ca430b94.jpg)

**Comment by rajarsheechatterjee** [comment]
That's because you have an older version. Uninstall the app and and install the [latest release](https://github.com/rajarsheechatterjee/lnreader/releases/tag/v1.0.17).

**Comment by rajarsheechatterjee** [comment]
@RoyalPK04 

Does this problem still exist?

**Comment by RoyalPK04** [comment]
I uninstalled and then reinstalled, but the problem still exists. I checked in the settings, it still says v16

**Comment by rajarsheechatterjee** [comment]
The about screen should show v1.0.17. Try clearing app data and see if it works.

**Comment by RoyalPK04** [comment]
The new update v18 works after clearing app data
