### ISSUE TITLE
[Feature request] Scrap data from MAL

### ISSUE THREAD

**Issue by SanOtaku09** [rajarsheechatterjee/lnreader#21]
Scrap data from this link
https://myanimelist.net/topmanga.php?type=lightnovels
It's myanimelist list link and this web page contains popular novels. 
When tapped on that scrapped novel start looking for that novel in global search
It will solve the limited novels in browse section
Browse only scrap limited novel which makes app a bit limited
It is a very nice app but many new reader who just started novels need help 
I'll hope u add this feature

Here's what I am talking about
-scrap novels from myanimelist popular novel webpage
-when tapped on those scrapped novel
-start a global search

**Comment by rajarsheechatterjee** [comment]
I have added both MyAnimeList and Novel Updates.

**Comment by rajarsheechatterjee** [comment]
Added in [v1.0.21](https://github.com/rajarsheechatterjee/lnreader/releases/tag/v1.0.21)
