### ISSUE TITLE
Swipe Gesture doesn't work

### ISSUE THREAD

**Issue by seizue** [rajarsheechatterjee/lnreader#27]
Idk if it's just my phone but swipe gesture doesn't work when I'm reading, I need to press > button in order for me to read the next chapter so hopefully this will be fix soon https://streamable.com/9xlnzj

also it would be nice if you add horizontal/vertical swipe gesture option in reader bottom sheet similar to this one :

![IMG_20210601_162321](https://user-images.githubusercontent.com/25120376/120296365-a0c7e700-c2fa-11eb-8fb0-a633c8c2c65b.jpg)

**Comment by rajarsheechatterjee** [comment]
Vertical swipe gesture to read the next chapter is not implemented.

Vertical/Horizontal swipe gesture options to switch between vertical and horizontal reading mode?

**Comment by seizue** [comment]
Oh okay. I thought my phone is having a problem xd

Yep that's right

**Comment by rajarsheechatterjee** [comment]
I have added swipe gestures to navigate between chapters. I will close this issue as there is another one about horizontal reading mode.
