### ISSUE TITLE
[Feature Request] Immersive mode

### ISSUE THREAD

**Issue by renatopdalencar** [rajarsheechatterjee/lnreader#28]
Hi! First of all, thank you for this amazing app!

Would an "Immersive mode" be possible? By that I mean an option that when activated, would hide the notification bar at the top when reading. I find the bar quite distracting when reading, especially because the text crosses it when scrolling.

**Comment by rajarsheechatterjee** [comment]
I have already added it. Should be there in next release.

https://user-images.githubusercontent.com/57822170/120883994-1800c200-c5fe-11eb-9bc9-591454bdc1b1.mp4

**Comment by renatopdalencar** [comment]
Wow, so fast. Thank you very much!
