### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SanOtaku09** [rajarsheechatterjee/lnreader#3]
It's a really nice copy of tachiyomi
And works really smooth
Gotta say U did a really good job
Keep working on this project & don't drop it
This project will become really popular I can already see it
Because it's way better than other novel apps I saw
People just need to notice that there is a app like this
I'll share your app with my friends

I'll rate this app 5/5 ⭐

**Comment by rajarsheechatterjee** [comment]
Thank you for your feedback. I was surprised someone actually found this app and used it. I am glad you liked it.
I will keep working on this project as your feedback has really motivated me.
