### ISSUE TITLE
Limit the reading

### ISSUE THREAD

**Issue by renatopdalencar** [rajarsheechatterjee/lnreader#30]
One last thing: I think it would be great if the reading area was limited to just a bit above the reading percentage at the bottom. This way, be it with the current vertical reading or the possible future horizontal/page by page reading method, the reading percentage wouldn't interfere with the text.

Sorry for all the three requests, and thanks again for the app and the great with you've been doing with it.

**Comment by rajarsheechatterjee** [comment]
I have already added an option to show/hide the reading percentage. I will also add some padding at bottom so that the text and the percentage don't overlap.

**Comment by renatopdalencar** [comment]
Awesome! I find the reading percentage very useful, so I'm looking forward for the padding. Thank you again.

**Comment by joseph619** [comment]
Please limit the padding to percentage mode only, users who don't want to see percentage would prefer the reader in fullscreen

**Comment by rajarsheechatterjee** [comment]
Added in [v1.0.21](https://github.com/rajarsheechatterjee/lnreader/releases/tag/v1.0.21)
