### ISSUE TITLE
[Feature Request] Darker bottom sheet in white reader background for better visibility

### ISSUE THREAD

**Issue by joseph619** [rajarsheechatterjee/lnreader#32]
As discussed on Discord

![IMG_20210604_114403](https://user-images.githubusercontent.com/34897862/121236760-497ac700-c864-11eb-9783-b28fff3ced2c.jpg)

**Comment by rajarsheechatterjee** [comment]
Added in [v1.0.21](https://github.com/rajarsheechatterjee/lnreader/releases/tag/v1.0.21)
