### ISSUE TITLE
[Feature Request] - Create online user system

### ISSUE THREAD

**Issue by freya50** [rajarsheechatterjee/lnreader#33]
I would like to be able to register and save my bookmarks so I don't lose my bookmarks on any device thanks :)

**Comment by joseph619** [comment]
Not possible unless rajarshee has a server (which costs money). This app is 100% free without ads, so no money.

**Comment by rajarsheechatterjee** [comment]
@freya50 Cross device sync is not planned. I will be improving how backups work so that bookmarks, progress, etc. don't get lost.

**Comment by ovizii** [comment]
maybe an auto-backup solution which can backup to some sort of online drive like onedrive or dropbox, etc. (on the second client there would be an auto-restore or a manual one)

any plans in this direction?
