### ISSUE TITLE
App just stops working

### ISSUE THREAD

**Issue by zishann** [rajarsheechatterjee/lnreader#36]
Whenever I try to download any novel the app just stops working or it lags and it gets stuck on the page where you can't even scroll. If the app works it works to slowly. Please fix this problem
App version:- Stable 1.0.21
Android 9

**Comment by rajarsheechatterjee** [comment]
@zishann This issue has been resolved, right?

**Comment by zishann** [comment]
Thanks man the app is working properly now after new update
