### ISSUE TITLE
[Bug] Crashing while selecting Reader from settings

### ISSUE THREAD

**Issue by BreadGenie** [rajarsheechatterjee/lnreader#44]
https://user-images.githubusercontent.com/63963181/124408736-77203680-dd64-11eb-91c6-b1508b13d295.mp4

LNReader: v1.1.1
Device: Asus ZenfonePro M1
OS: Android 10

**Comment by rajarsheechatterjee** [comment]
Try changing themes in reader bottom sheet and then open reader settings.

**Comment by BreadGenie** [comment]
That fixed it!
Thanks!
