### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SanOtaku09** [rajarsheechatterjee/lnreader#5]
![Screenshot_2021-04-28-17-23-48-141_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/61407097/116399523-a4bda080-a846-11eb-9aa7-108e68551105.jpg)

There are only few light novels in browse section
Browse section isn't showing all novels present in site
When searched novel show up but don't show up in browse section

All the sources does this

**Comment by joseph619** [comment]
Edit the title and mention what bug it is there in brief

**Comment by rajarsheechatterjee** [comment]
@SanOtaku09 The browse screen scrapes novels from the latest or top novels page of the source . For example https://boxnovel.com/novel/?m_orderby=rating or https://www.readlightnovel.org/top-novel.
It can only display the novels which are on that page.
